/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    branches: Branch;
    doctors: Doctor;
    programs: Program;
    articles: Article;
    awards: Award;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('th' | 'en') | ('th' | 'en')[];
  globals: {
    membership: Membership;
    ecosystem: Ecosystem;
    'home-hero': HomeHero;
  };
  globalsSelect: {
    membership: MembershipSelect<false> | MembershipSelect<true>;
    ecosystem: EcosystemSelect<false> | EcosystemSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
  };
  locale: 'th' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'medical-reviewer';
  /**
   * สาขาที่ผู้ใช้คนนี้ดูแล — ใช้จำกัดสิทธิ์แก้ไข/ลบข้อมูลเฉพาะสาขาที่เลือก (Admin ไม่ต้องตั้งค่านี้ เพราะเข้าถึงได้ทุกสาขาอยู่แล้ว)
   */
  assignedBranches?: (number | Branch)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  /**
   * e.g. sanampao, phaholyothin, sriayudhaya, sriracha, petchakasem
   */
  slug: string;
  nameTh: string;
  nameEn: string;
  /**
   * e.g. "Hospital-Grade Plastic Surgery Center"
   */
  tagline?: string | null;
  description?: string | null;
  address?: string | null;
  hours?: string | null;
  phone?: string | null;
  lineId?: string | null;
  /**
   * Google Maps link or embed URL (not present on current site — recommended addition)
   */
  mapUrl?: string | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Facility highlight cards, e.g. "Positive Pressure Operating Theaters"
   */
  facilities?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * BTS/parking directions shown on the branch detail page
   */
  directions?: string | null;
  /**
   * Doctors featured on this branch page (also filterable via Doctor.branch)
   */
  doctors?: (number | Doctor)[] | null;
  featuredPrograms?: (number | Program)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  /**
   * URL for the doctor page, e.g. /doctor/dr-punnawit-sirimetha. Leave blank to auto-generate from Name En, or type your own custom URL.
   */
  slug?: string | null;
  nameTh: string;
  nameEn: string;
  branch: number | Branch;
  /**
   * Filter key used on doctor.html (matches the 4 Beaugevity pillars)
   */
  specialty: 'plastic' | 'dermatology' | 'longevity' | 'wellness';
  /**
   * Display text on the card, e.g. "ศัลยกรรมตกแต่งรอบดวงตาและใบหน้า"
   */
  specialtyLabel?: string | null;
  /**
   * Small credential line under the specialty, e.g. "Board Certified Plastic Surgeon"
   */
  subNote?: string | null;
  /**
   * Large portrait for doctor_detail hero
   */
  portrait?: (number | null) | Media;
  /**
   * Thumbnail for listing/carousel cards
   */
  cardPhoto?: (number | null) | Media;
  /**
   * Hero badge on doctor_detail, e.g. "แพทย์ประจำศูนย์ศัลยกรรมตกแต่ง โรงพยาบาลพญาไทศรีราชา"
   */
  hospitalTitle?: string | null;
  /**
   * Sub-title under the doctor name, e.g. "วุฒิบัตรสาขาศัลยศาสตร์ตกแต่ง..."
   */
  boardCertification?: string | null;
  /**
   * Pill tags on the profile header, e.g. "✦ Plastic Surgery"
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. "Education & Certifications", "Professional Experience", "Clinical Specialization"
   */
  credentialGroups?:
    | {
        heading: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Weekly outpatient schedule table
   */
  schedule?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * e.g. "09:00 - 20:00 น."
         */
        hours: string;
        locationName?: string | null;
        locationNote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Paragraph inviting appointment requests on the doctor page
   */
  contactIntro?: string | null;
  /**
   * e.g. "ศูนย์ศัลยกรรมตกแต่ง · โรงพยาบาลพญาไทศรีราชา"
   */
  contactFact?: string | null;
  seo?: {
    /**
     * Browser tab title / Google search result title. Leave blank to use the page title.
     */
    title?: string | null;
    /**
     * Google search result snippet (~150–160 characters). Leave blank to use the page summary.
     */
    description?: string | null;
    /**
     * Preview image shown when this page is shared on LINE, Facebook, or Twitter. Leave blank to use the page's own cover image.
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from Google search results (the page itself stays live and reachable by direct link).
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  /**
   * e.g. pv01 — used in program_detail.html?id=
   */
  slug: string;
  /**
   * e.g. "PV · 01"
   */
  code?: string | null;
  category: 'plastic' | 'dermatology' | 'longevity' | 'wellness';
  title: string;
  /**
   * THB
   */
  price: number;
  /**
   * Show in the /program highlight carousel (program.html originally hardcoded pv01, pv02, pv03, pv06 here)
   */
  featured?: boolean | null;
  /**
   * Leave blank if this program is available at every branch.
   */
  branch?: (number | null) | Branch;
  /**
   * e.g. "รับบริการได้ถึง 30/12/69"
   */
  validityNote?: string | null;
  /**
   * Card badge, e.g. "LONGEVITY", "CARDIOVASCULAR", "CELLULAR HEALTH"
   */
  tag?: string | null;
  /**
   * Catalog card description
   */
  shortDescription?: string | null;
  /**
   * 2 bullet points shown on the catalog card
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "ปรึกษาแพทย์พร้อมสรุปผล", "เหมาะสำหรับทุกเพศ"
   */
  cardNote?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Hidden keywords for the catalog search box
   */
  searchKeywords?: string | null;
  /**
   * Full "เกี่ยวกับโปรแกรมตรวจ" description on the detail page
   */
  aboutProgram?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * "ตรวจเพื่ออะไร" bullet list
   */
  purposeList?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * "เหมาะกับใคร" bullet list
   */
  audienceList?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Checkup table rows; use "group" to split male/female lists like PV·02
   */
  checkupItems?:
    | {
        group?: ('all' | 'male' | 'female') | null;
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  termsOfService?:
    | {
        title?: string | null;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional override of the branch’s default contact info (used by pv02 today)
   */
  contactOverride?: {
    location?: string | null;
    hours?: string | null;
    phone?: string | null;
  };
  seo?: {
    /**
     * Browser tab title / Google search result title. Leave blank to use the page title.
     */
    title?: string | null;
    /**
     * Google search result snippet (~150–160 characters). Leave blank to use the page summary.
     */
    description?: string | null;
    /**
     * Preview image shown when this page is shared on LINE, Facebook, or Twitter. Leave blank to use the page's own cover image.
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from Google search results (the page itself stays live and reachable by direct link).
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * e.g. blue-ocean-pathway — used in article_detail.html?id=
   */
  slug: string;
  title: string;
  /**
   * Card excerpt + meta description base
   */
  summary?: string | null;
  category: 'longevity' | 'dermatology' | 'plastic' | 'wellness';
  /**
   * Display badge, e.g. "เวชศาสตร์อายุยืนยาว"
   */
  categoryLabel?: string | null;
  /**
   * Optional — only set this if the article is specific to one branch. Leave blank for general editorial content.
   */
  branch?: (number | null) | Branch;
  coverImage: number | Media;
  publishedDate: string;
  readTimeMinutes: number;
  /**
   * Surface in the "MOST READ" sidebar
   */
  popular?: boolean | null;
  /**
   * Main prose. H2 sections build the table of contents automatically; use blocks below for note-box / insight-grid components seen on the current site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional numbered "process" cards (e.g. the 4-step Blue Ocean Pathway grid)
   */
  insightSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional callout box, e.g. "สิ่งสำคัญที่ควรรู้"
   */
  noteBox?: {
    heading?: string | null;
    text?: string | null;
  };
  author?: {
    name?: string | null;
    role?: string | null;
    avatar?: (number | null) | Media;
    /**
     * Optional link to a specific doctor byline
     */
    doctor?: (number | null) | Doctor;
  };
  tags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  relatedPrograms?: (number | Program)[] | null;
  relatedDoctors?: (number | Doctor)[] | null;
  seo?: {
    /**
     * Browser tab title / Google search result title. Leave blank to use the page title.
     */
    title?: string | null;
    /**
     * Google search result snippet (~150–160 characters). Leave blank to use the page summary.
     */
    description?: string | null;
    /**
     * Preview image shown when this page is shared on LINE, Facebook, or Twitter. Leave blank to use the page's own cover image.
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from Google search results (the page itself stays live and reachable by direct link).
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  image: number | Media;
  /**
   * e.g. "COVID Management Initiative of the Year - Thailand · Healthcare Asia Awards 2022"
   */
  caption: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Booking requests submitted through the VIP Concierge modal and doctor appointment forms across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  /**
   * Branch slug selected in the modal, e.g. "sanampao" (not a relationship — see field comment)
   */
  branch: string;
  service: 'plastic-surgery' | 'longevity' | 'dermatology' | 'wellness' | 'membership';
  /**
   * Free-text notes/preferred time. Pre-filled with doctor/program context when the modal was opened from a specific card (see triggerContext() in vip-modal.js).
   */
  notes?: string | null;
  /**
   * Only set by the doctor detail page's own appointment form (public/js/doctor-appointment-form.js) — the shared VIP modal has no date field, so this stays empty for those leads.
   */
  preferredDate?: string | null;
  /**
   * Page path the form was submitted from, e.g. /program/pv02 — for triage context, not shown to the visitor.
   */
  sourcePath?: string | null;
  /**
   * Internal triage status — not visible to the visitor.
   */
  status: 'new' | 'contacted' | 'booked' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  assignedBranches?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  slug?: T;
  nameTh?: T;
  nameEn?: T;
  tagline?: T;
  description?: T;
  address?: T;
  hours?: T;
  phone?: T;
  lineId?: T;
  mapUrl?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  facilities?:
    | T
    | {
        text?: T;
        id?: T;
      };
  directions?: T;
  doctors?: T;
  featuredPrograms?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  slug?: T;
  nameTh?: T;
  nameEn?: T;
  branch?: T;
  specialty?: T;
  specialtyLabel?: T;
  subNote?: T;
  portrait?: T;
  cardPhoto?: T;
  hospitalTitle?: T;
  boardCertification?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  bio?: T;
  credentialGroups?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  schedule?:
    | T
    | {
        day?: T;
        hours?: T;
        locationName?: T;
        locationNote?: T;
        id?: T;
      };
  contactIntro?: T;
  contactFact?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  slug?: T;
  code?: T;
  category?: T;
  title?: T;
  price?: T;
  featured?: T;
  branch?: T;
  validityNote?: T;
  tag?: T;
  shortDescription?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cardNote?: T;
  heroImage?: T;
  searchKeywords?: T;
  aboutProgram?: T;
  purposeList?:
    | T
    | {
        text?: T;
        id?: T;
      };
  audienceList?:
    | T
    | {
        text?: T;
        id?: T;
      };
  checkupItems?:
    | T
    | {
        group?: T;
        name?: T;
        description?: T;
        id?: T;
      };
  termsOfService?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  contactOverride?:
    | T
    | {
        location?: T;
        hours?: T;
        phone?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  summary?: T;
  category?: T;
  categoryLabel?: T;
  branch?: T;
  coverImage?: T;
  publishedDate?: T;
  readTimeMinutes?: T;
  popular?: T;
  body?: T;
  insightSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  noteBox?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  author?:
    | T
    | {
        name?: T;
        role?: T;
        avatar?: T;
        doctor?: T;
      };
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  relatedPrograms?: T;
  relatedDoctors?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  branch?: T;
  service?: T;
  notes?: T;
  preferredDate?: T;
  sourcePath?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership".
 */
export interface Membership {
  id: number;
  hero: {
    kicker?: string | null;
    headline: string;
    lead?: string | null;
    heroImage?: (number | null) | Media;
  };
  intro?: {
    overline?: string | null;
    heading?: string | null;
    body?: string | null;
  };
  /**
   * The 4 "AUM Privileges" cards
   */
  privileges?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * "The AUM Promise" quote section
   */
  promise?: {
    image?: (number | null) | Media;
    quote?: string | null;
    body?: string | null;
  };
  /**
   * The 4-step "Your Membership Journey" list
   */
  journeySteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  finalCta?: {
    overline?: string | null;
    heading?: string | null;
    body?: string | null;
    buttonLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem".
 */
export interface Ecosystem {
  id: number;
  hero: {
    eyebrow?: string | null;
    headlineLine1: string;
    headlineLine2: string;
    lead?: string | null;
  };
  /**
   * Exactly 4 rows, in order: Longevity, Dermatology, Aesthetic Wellness, Plastic Surgery.
   */
  disciplines?:
    | {
        eyebrow: string;
        title: string;
        subtitle: string;
        description: string;
        chips?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        doctorLinkLabel: string;
        programLinkLabel: string;
        articleLinkLabel: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  closingCta: {
    eyebrow?: string | null;
    heading: string;
    body?: string | null;
    buttonLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  eyebrow?: string | null;
  headline: string;
  lead?: string | null;
  ctaLabel?: string | null;
  /**
   * Rotating hero background slideshow (public/js/main.js cross-fades between these every 7s).
   */
  backgroundImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership_select".
 */
export interface MembershipSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        headline?: T;
        lead?: T;
        heroImage?: T;
      };
  intro?:
    | T
    | {
        overline?: T;
        heading?: T;
        body?: T;
      };
  privileges?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  promise?:
    | T
    | {
        image?: T;
        quote?: T;
        body?: T;
      };
  journeySteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  finalCta?:
    | T
    | {
        overline?: T;
        heading?: T;
        body?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem_select".
 */
export interface EcosystemSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        lead?: T;
      };
  disciplines?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        chips?:
          | T
          | {
              label?: T;
              id?: T;
            };
        doctorLinkLabel?: T;
        programLinkLabel?: T;
        articleLinkLabel?: T;
        image?: T;
        id?: T;
      };
  closingCta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  lead?: T;
  ctaLabel?: T;
  backgroundImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}