// One-off backfill for the multi-branch doctor CR ("หมอ 1 profile หลายสาขา").
// Copies each existing doctor's single `branch` into the new `branches`
// (hasMany) + `mainBranch` fields, and wraps the existing flat `schedule`
// array into the new per-branch `scheduleByBranch` structure — see
// cms/collections/Doctors.ts's comments on those fields for the full
// picture. Does NOT touch/remove the legacy `branch`/`schedule` fields.
//
// Idempotent: skips any doctor that already has `branches` (or
// `scheduleByBranch`) populated, so it's safe to re-run — e.g. once now
// locally, then again after deploying to production.
//
// This does NOT merge the duplicate doctor records that exist today (same
// real person filed as a separate doc per branch) — that merge is a manual,
// per-doctor decision an admin makes in the CMS (pick a survivor doc, add
// the other branches to it, unpublish the rest), on purpose, since matching
// by name risks merging two different doctors who happen to share a name.
// This script only gets every doctor's *own* existing branch/schedule data
// safely mirrored into the new fields so that manual merge has something
// correct to start from.
//
// Run with: npx tsx cms/scripts/backfillDoctorBranches.ts
// (requires your local Postgres — same DATABASE_URI your dev server uses —
// to be reachable, so run this on your own machine, not in a sandbox.)
import 'dotenv/config'

import { getPayload } from 'payload'

import { LOCALE_META } from '../admin/localeMeta'
import config from '../payload.config'

import type { Config, Doctor } from '../../payload-types'

// The generated `Config['locale']` union is the source of truth for valid
// locale codes — LOCALE_META's `code` is plain `string`, so this cast is
// safe as long as it stays in sync with payload.config.ts's
// `localization.locales` (same assumption LanguageSettings.ts already
// relies on).
const ALL_LOCALES = ['th', ...LOCALE_META.map((l) => l.code)] as Config['locale'][]

function idOf(value: unknown): number | undefined {
  if (value === null || value === undefined) return undefined
  const id = typeof value === 'object' ? (value as { id: number }).id : value
  return typeof id === 'number' ? id : Number(id) || undefined
}

// Payload re-validates the ENTIRE document (every field, every locale it
// touches) on every update — including unrelated fields we're not writing
// to. Some existing doctors have long-standing incomplete translations
// (e.g. "ประวัติและวุฒิบัตร" credential tags/groups left blank in a locale
// that was never fully translated), which makes that locale's document
// fail validation the moment ANYTHING tries to save it — not something
// this backfill caused. Rather than let one bad doctor/locale crash the
// whole run, catch and skip, and report a summary at the end so those
// pre-existing data gaps can be fixed by hand afterward.
function summarizeError(err: unknown): string {
  if (err && typeof err === 'object' && 'data' in err) {
    const data = (err as { data?: { errors?: Array<{ path?: string; message?: string }> } }).data
    const errors = data?.errors
    if (Array.isArray(errors) && errors.length) {
      return errors.map((e) => e.path).filter(Boolean).join(', ')
    }
  }
  return err instanceof Error ? err.message : String(err)
}

async function main() {
  const payload = await getPayload({ config })

  const { docs } = await payload.find({
    collection: 'doctors',
    limit: 1000,
    depth: 0,
    // draft: true so unpublished doctors still get backfilled too.
    draft: true,
    overrideAccess: true,
  })

  let branchesUpdated = 0
  let scheduleUpdated = 0
  let skippedNoBranch = 0
  const branchesFailed: Array<{ id: number; error: string }> = []
  const scheduleFailed: Array<{ id: number; locale: string; error: string }> = []

  for (const doc of docs) {
    const d = doc as unknown as Record<string, unknown>
    const branchId = idOf(d.branch)

    if (!branchId) {
      // Shouldn't happen (branch is required today) but don't crash the
      // whole run over one bad record.
      skippedNoBranch += 1
      continue
    }

    const alreadyHasBranches = Array.isArray(d.branches) && d.branches.length > 0
    if (!alreadyHasBranches) {
      try {
        // eslint-disable-next-line no-await-in-loop
        await payload.update({
          collection: 'doctors',
          // TS's generated ByID overload for update/findByID also accepts a
          // "select"-shaped object in place of a plain id, which — given only
          // a bare number here — it shouldn't ever actually match; the `as
          // number` just short-circuits that ambiguous overload resolution.
          id: doc.id as number,
          data: { branches: [branchId], mainBranch: branchId },
          overrideAccess: true,
          // Copying existing values into new fields isn't new editorial
          // content, so it shouldn't create a fresh draft revision to review
          // — same reasoning as backfillLocalizedNames.ts.
          draft: false,
        })
        branchesUpdated += 1
      } catch (err) {
        branchesFailed.push({ id: doc.id as number, error: summarizeError(err) })
      }
    }

    const alreadyHasSchedule = Array.isArray(d.scheduleByBranch) && d.scheduleByBranch.length > 0
    if (!alreadyHasSchedule) {
      let wroteAnyLocale = false
      for (const locale of ALL_LOCALES) {
        try {
          // eslint-disable-next-line no-await-in-loop
          const localized = await payload.findByID({
            collection: 'doctors',
            id: doc.id as number,
            depth: 0,
            locale,
            draft: true,
            overrideAccess: true,
          })
          const rows: NonNullable<Doctor['schedule']> = Array.isArray(localized.schedule) ? localized.schedule : []
          if (!rows.length) continue

          // eslint-disable-next-line no-await-in-loop
          await payload.update({
            collection: 'doctors',
            id: doc.id as number,
            locale,
            data: {
              scheduleByBranch: [
                {
                  branch: branchId,
                  rows: rows.map((row) => ({
                    day: row.day,
                    hours: row.hours,
                    locationName: row.locationName,
                    locationNote: row.locationNote,
                  })),
                },
              ],
            },
            overrideAccess: true,
            draft: false,
          })
          wroteAnyLocale = true
        } catch (err) {
          scheduleFailed.push({ id: doc.id as number, locale, error: summarizeError(err) })
        }
      }
      if (wroteAnyLocale) scheduleUpdated += 1
    }
  }

  console.log(
    `[backfill] doctors: branches/mainBranch set on ${branchesUpdated}/${docs.length}, ` +
      `scheduleByBranch set on ${scheduleUpdated}/${docs.length}` +
      (skippedNoBranch ? `, skipped ${skippedNoBranch} with no branch set` : ''),
  )
  if (branchesFailed.length) {
    console.warn(`[backfill] branches/mainBranch FAILED on ${branchesFailed.length} doctor(s) — pre-existing data issues, not caused by this script:`)
    for (const f of branchesFailed) console.warn(`  - doctor id ${f.id}: ${f.error}`)
  }
  if (scheduleFailed.length) {
    console.warn(`[backfill] scheduleByBranch FAILED on ${scheduleFailed.length} doctor/locale pair(s):`)
    for (const f of scheduleFailed) console.warn(`  - doctor id ${f.id} [${f.locale}]: ${f.error}`)
  }
  process.exit(0)
}

main().catch((err) => {
  console.error('[backfill] failed:', err)
  process.exit(1)
})
