import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // NOTE: this file was generated by `payload migrate:create`, which diffs
  // config against the last hand-maintained JSON snapshot — it has no idea
  // dev-mode auto-push already created most of this live (see
  // 20260824_110000.ts's header comment for why member_privileges_rels was
  // deliberately left out of that snapshot). Every statement below was
  // hand-edited to add IF EXISTS/IF NOT EXISTS/exception guards so this is
  // safe to run whether or not auto-push got there first.
  await db.execute(sql`
   CREATE TABLE IF NOT EXISTS "member_privileges_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"membership_tiers_id" integer
  );

  DROP TABLE IF EXISTS "member_privileges_cards_tiers" CASCADE;
  ALTER TABLE "members" ALTER COLUMN "first_name" DROP NOT NULL;
  ALTER TABLE "members" ALTER COLUMN "last_name" DROP NOT NULL;
  ALTER TABLE "members" ALTER COLUMN "phone" DROP NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "intro_eyebrow" SET DEFAULT 'WHY PHIVARA EXISTS';
  ALTER TABLE "home_hero_locales" ALTER COLUMN "intro_quote" SET NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "intro_tagline" SET DEFAULT '— The Art of Beaugevity';
  ALTER TABLE "home_hero_locales" ALTER COLUMN "expertise_eyebrow" SET DEFAULT 'INTEGRATED EXPERTISE';
  ALTER TABLE "home_hero_locales" ALTER COLUMN "expertise_headline" SET NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "destinations_eyebrow" SET DEFAULT 'PHIVARA DESTINATIONS';
  ALTER TABLE "home_hero_locales" ALTER COLUMN "destinations_headline" SET NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "specialists_eyebrow" SET DEFAULT 'OUR SPECIALISTS';
  ALTER TABLE "home_hero_locales" ALTER COLUMN "specialists_headline" SET NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "journal_eyebrow" SET DEFAULT 'THE JOURNAL';
  ALTER TABLE "home_hero_locales" ALTER COLUMN "journal_headline" SET NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "awards_eyebrow" SET DEFAULT 'AWARDS & RECOGNITION';
  ALTER TABLE "home_hero_locales" ALTER COLUMN "awards_headline" SET NOT NULL;
  ALTER TABLE "membership_tiers" ALTER COLUMN "order" SET DATA TYPE numeric;
  ALTER TABLE "membership_tiers" ALTER COLUMN "gradient_start" SET DEFAULT '#2C2313';
  ALTER TABLE "membership_tiers" ALTER COLUMN "gradient_mid" SET DEFAULT '#C7A76B';
  ALTER TABLE "membership_tiers" ALTER COLUMN "gradient_end" SET DEFAULT '#2C2313';
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN IF NOT EXISTS "membership_tiers_id" integer;

  DO $$ BEGIN
    ALTER TABLE "member_privileges_rels" ADD CONSTRAINT "member_privileges_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."member_privileges"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION
    WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
    ALTER TABLE "member_privileges_rels" ADD CONSTRAINT "member_privileges_rels_membership_tiers_fk" FOREIGN KEY ("membership_tiers_id") REFERENCES "public"."membership_tiers"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION
    WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "member_privileges_rels_order_idx" ON "member_privileges_rels" USING btree ("order");
  CREATE INDEX IF NOT EXISTS "member_privileges_rels_parent_idx" ON "member_privileges_rels" USING btree ("parent_id");
  CREATE INDEX IF NOT EXISTS "member_privileges_rels_path_idx" ON "member_privileges_rels" USING btree ("path");
  CREATE INDEX IF NOT EXISTS "member_privileges_rels_membership_tiers_id_idx" ON "member_privileges_rels" USING btree ("membership_tiers_id");
  DO $$ BEGIN
    ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_membership_tiers_fk" FOREIGN KEY ("membership_tiers_id") REFERENCES "public"."membership_tiers"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION
    WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_membership_tiers_id_idx" ON "payload_locked_documents_rels" USING btree ("membership_tiers_id");
  DROP TYPE IF EXISTS "public"."enum_member_privileges_cards_tiers";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DO $$ BEGIN
    CREATE TYPE "public"."enum_member_privileges_cards_tiers" AS ENUM('silver', 'gold', 'diamond');
  EXCEPTION
    WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "member_privileges_cards_tiers" (
  	"order" integer NOT NULL,
  	"parent_id" varchar NOT NULL,
  	"value" "enum_member_privileges_cards_tiers" NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL
  );

  DROP TABLE IF EXISTS "member_privileges_rels" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_membership_tiers_fk";

  DROP INDEX IF EXISTS "payload_locked_documents_rels_membership_tiers_id_idx";
  ALTER TABLE "members" ALTER COLUMN "first_name" SET NOT NULL;
  ALTER TABLE "members" ALTER COLUMN "last_name" SET NOT NULL;
  ALTER TABLE "members" ALTER COLUMN "phone" SET NOT NULL;
  ALTER TABLE "membership_tiers" ALTER COLUMN "order" SET DATA TYPE integer;
  ALTER TABLE "membership_tiers" ALTER COLUMN "gradient_start" DROP DEFAULT;
  ALTER TABLE "membership_tiers" ALTER COLUMN "gradient_mid" DROP DEFAULT;
  ALTER TABLE "membership_tiers" ALTER COLUMN "gradient_end" DROP DEFAULT;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "intro_eyebrow" DROP DEFAULT;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "intro_quote" DROP NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "intro_tagline" DROP DEFAULT;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "expertise_eyebrow" DROP DEFAULT;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "expertise_headline" DROP NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "destinations_eyebrow" DROP DEFAULT;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "destinations_headline" DROP NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "specialists_eyebrow" DROP DEFAULT;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "specialists_headline" DROP NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "journal_eyebrow" DROP DEFAULT;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "journal_headline" DROP NOT NULL;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "awards_eyebrow" DROP DEFAULT;
  ALTER TABLE "home_hero_locales" ALTER COLUMN "awards_headline" DROP NOT NULL;
  DO $$ BEGIN
    ALTER TABLE "member_privileges_cards_tiers" ADD CONSTRAINT "member_privileges_cards_tiers_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."member_privileges_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION
    WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "member_privileges_cards_tiers_order_idx" ON "member_privileges_cards_tiers" USING btree ("order");
  CREATE INDEX IF NOT EXISTS "member_privileges_cards_tiers_parent_idx" ON "member_privileges_cards_tiers" USING btree ("parent_id");
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN IF EXISTS "membership_tiers_id";`)
}
